/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SQL;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import java.sql.SQLException;
/**
 *
 * @author Daniel Cruz Regino
 */
public class Conexion_SQL extends javax.swing.JFrame {

    /**
     * Creates new form Conexion_SQL
     */
    public Conexion_SQL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnConsulta_A = new javax.swing.JButton();
        btnConsulta_B = new javax.swing.JButton();
        btnConsulta_C = new javax.swing.JButton();
        btnConsulta_D = new javax.swing.JButton();
        btnConsulta_E = new javax.swing.JButton();
        btnConsulta_F = new javax.swing.JButton();
        btnConsulta_G = new javax.swing.JButton();
        btnConsulta_H = new javax.swing.JButton();
        btnConsulta_I = new javax.swing.JButton();
        btnConsulta_J = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnConsulta_A.setText("Consulta_A");
        btnConsulta_A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_AActionPerformed(evt);
            }
        });

        btnConsulta_B.setText("Consulta_B");
        btnConsulta_B.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_BActionPerformed(evt);
            }
        });

        btnConsulta_C.setText("Consulta_C");
        btnConsulta_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_CActionPerformed(evt);
            }
        });

        btnConsulta_D.setText("Consulta_D");
        btnConsulta_D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_DActionPerformed(evt);
            }
        });

        btnConsulta_E.setText("Consulta_E");
        btnConsulta_E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_EActionPerformed(evt);
            }
        });

        btnConsulta_F.setText("Consulta_F");
        btnConsulta_F.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_FActionPerformed(evt);
            }
        });

        btnConsulta_G.setText("Consulta_G");
        btnConsulta_G.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_GActionPerformed(evt);
            }
        });

        btnConsulta_H.setText("Consulta_H");
        btnConsulta_H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_HActionPerformed(evt);
            }
        });

        btnConsulta_I.setText("Consulta_I");
        btnConsulta_I.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_IActionPerformed(evt);
            }
        });

        btnConsulta_J.setText("Consulta_J");
        btnConsulta_J.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsulta_JActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Categoria:");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Región:");

        jLabel3.setText("Territorio:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel4.setText("ID Orden:");

        jLabel5.setText("Cantidad:");

        jLabel6.setText("Num_Metodo:");

        jLabel7.setText("ID Orden:");

        jLabel8.setText("Email:");

        jLabel9.setText("Cliente ID:");

        jLabel10.setText("Fecha_I:");

        jLabel11.setText("Fecha_F:");

        jLabel12.setText("Fecha_I:");

        jLabel13.setText("Fecha_F:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta_A)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(btnConsulta_B, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta_D)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)))
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField4)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btnConsulta_E)
                                .addGap(91, 91, 91)
                                .addComponent(btnConsulta_F)))
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsulta_J)
                        .addGap(83, 83, 83)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta_G)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnConsulta_C)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnConsulta_H)
                .addGap(138, 138, 138)
                .addComponent(btnConsulta_I)
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta_A)
                    .addComponent(btnConsulta_B)
                    .addComponent(btnConsulta_C)
                    .addComponent(btnConsulta_D))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta_E)
                    .addComponent(btnConsulta_F)
                    .addComponent(btnConsulta_G))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsulta_I)
                    .addComponent(btnConsulta_H))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(btnConsulta_J)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsulta_AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_AActionPerformed
        // TODO add your handling code here:
        String bases = "TerritoryID    Total_Ventas";
        int j = Integer.parseInt(jTextField1.getText());
        switch(j){
            case 1:
                try{         
               Statement sql = Conexion.getConexion().createStatement();
               String consulta = "{call sp_Consulta1(1)}";
               ResultSet resultado = sql.executeQuery(consulta);
        
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                   " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            case 2:
                try{         
               Statement sql = Conexion.getConexion().createStatement();
               String consulta = "{call sp_Consulta1(2)}";
               ResultSet resultado = sql.executeQuery(consulta);
        
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                   " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            case 3:
                try{         
               Statement sql = Conexion.getConexion().createStatement();
               String consulta = "{call sp_Consulta1(3)}";
               ResultSet resultado = sql.executeQuery(consulta);
        
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                   " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            case 4:
                try{         
               Statement sql = Conexion.getConexion().createStatement();
               String consulta = "{call sp_Consulta1(4)}";
               ResultSet resultado = sql.executeQuery(consulta);
        
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                   " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            default:
        }
        
    }//GEN-LAST:event_btnConsulta_AActionPerformed

    private void btnConsulta_BActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_BActionPerformed
        // TODO add your handling code here:
        String k = jTextField2.getText();
        String bases = "Group               ProductID    columna";
        switch(k){
            case "Europe":
                try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta2(N'Europe')}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "             " + resultado.getString(2) + "          " + resultado.getString(3) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            case "North America":
                try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta2(N'North America')}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "      " + resultado.getString(2) + "          " + resultado.getString(3) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            case "Pacific":
                try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta2(N'Pacific')}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "              " + resultado.getString(2) + "          " + resultado.getString(3) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
                break;
            default:
        }
        
    }//GEN-LAST:event_btnConsulta_BActionPerformed

    private void btnConsulta_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_CActionPerformed
        // TODO add your handling code here:
        String bases = "";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta3(50,6)}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += resultado.getString(1) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_CActionPerformed

    private void btnConsulta_DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_DActionPerformed
        // TODO add your handling code here:
        int l = Integer.parseInt(jTextField3.getText());
        String bases = "Num_Clientes";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta4("+ l +")}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_DActionPerformed

    private void btnConsulta_EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_EActionPerformed
        // TODO add your handling code here:
        int m = Integer.parseInt(jTextField4.getText());
        int n = Integer.parseInt(jTextField5.getText());
        String bases = "Cantidad_prod  ID_Orden";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta5(" + m + "," + n + ")}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                         " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_EActionPerformed

    private void btnConsulta_FActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_FActionPerformed
        // TODO add your handling code here:
        int o = Integer.parseInt(jTextField6.getText());
        int p = Integer.parseInt(jTextField7.getText());
        String bases = "Metodo_envio      ID_Metodo   ID_Metodo_Sel   SalesOrderID";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta6(" + o + "," + p + ")}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "    " + 
                        resultado.getString(2) + "                   " + resultado.getString(3) + 
                        "                          " + resultado.getString(4)+ "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_FActionPerformed

    private void btnConsulta_GActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_GActionPerformed
        // TODO add your handling code here:
        int q = Integer.parseInt(jTextField9.getText());
        String r = jTextField8.getText();
        String bases = "ID_cliente   Email";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            //N'Hugo0@adventure-works.com'
            String consulta = "{call sp_Consulta7(N'" + r + "'," + q + ")}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                 " + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_GActionPerformed

    private void btnConsulta_HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_HActionPerformed
        // TODO add your handling code here:
        String bases = "TerritoryID  SalesPersonID    FirstName     LastName            Total_Pedidos";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta8()}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                 " 
                        + resultado.getString(2) + "                    " 
                        + resultado.getString(3) + "                     "
                        + resultado.getString(4) + "                    "
                        + resultado.getString(5) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_HActionPerformed

    private void btnConsulta_IActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_IActionPerformed
        // TODO add your handling code here:
        String s = jTextField10.getText();
        String t = jTextField11.getText();
        String bases = "TerritoryID   Total_ventas";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta9('" + s + "','" + t + "')}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                  " 
                        + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_IActionPerformed

    private void btnConsulta_JActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsulta_JActionPerformed
        // TODO add your handling code here:
        String u = jTextField12.getText();
        String v = jTextField13.getText();
        String bases = "ProductID   Cantidad_productos";
        try{
            Statement sql = Conexion.getConexion().createStatement();
            
            String consulta = "{call sp_Consulta10('" + u + "','" + v + "')}";
            ResultSet resultado = sql.executeQuery(consulta);
            
            while(resultado.next()){
                bases += "\n" + resultado.getString(1)+ "                  " 
                        + resultado.getString(2) + "\n";
                
            }
            
            JOptionPane.showMessageDialog(null, bases);
            
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnConsulta_JActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conexion_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conexion_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conexion_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conexion_SQL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conexion_SQL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta_A;
    private javax.swing.JButton btnConsulta_B;
    private javax.swing.JButton btnConsulta_C;
    private javax.swing.JButton btnConsulta_D;
    private javax.swing.JButton btnConsulta_E;
    private javax.swing.JButton btnConsulta_F;
    private javax.swing.JButton btnConsulta_G;
    private javax.swing.JButton btnConsulta_H;
    private javax.swing.JButton btnConsulta_I;
    private javax.swing.JButton btnConsulta_J;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
